# Generated by Django 2.2.5 on 2019-09-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_created=True)),
                ('priority', models.IntegerField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000000)),
                ('last_edit', models.DateTimeField()),
            ],
        ),
    ]
