# Generated by Django 2.2.5 on 2019-10-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_post_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
